# Generated by Django 4.0.4 on 2022-04-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(default='traveltourhotel.jpg', upload_to='room'),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(default='traveltourhotel.jpg', upload_to='room'),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.ImageField(default='traveltourhotel.jpg', upload_to='room'),
        ),
        migrations.AddField(
            model_name='room',
            name='image4',
            field=models.ImageField(default='traveltourhotel.jpg', upload_to='room'),
        ),
        migrations.AddField(
            model_name='room',
            name='image5',
            field=models.ImageField(default='traveltourhotel.jpg', upload_to='room'),
        ),
    ]
