# Generated by Django 4.0.4 on 2022-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_image1_room_image2_room_image3_room_image4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image5',
        ),
        migrations.AddField(
            model_name='booking',
            name='item_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='order_no',
            field=models.IntegerField(default=1),
        ),
    ]
