# Generated by Django 4.0.4 on 2022-04-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_booking_no_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order_no',
            field=models.CharField(max_length=36),
        ),
    ]
