# Generated by Django 4.0.4 on 2022-04-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
