# Generated by Django 4.0.4 on 2022-06-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_room_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
