# Generated by Django 4.0.4 on 2022-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_room_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bannerword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
