# Generated by Django 4.0.4 on 2022-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_bannerword_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerword',
            name='slogan',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
