# Generated by Django 4.0.4 on 2022-07-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal',
            new_name='title',
        ),
    ]
